apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: prometheus
  annotations:
    github.com/project-slug: anamness/prometheus
spec:
  type: other
  lifecycle: experimental
  owner: guests
